# Generated by Django 3.0.8 on 2020-09-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/no_image.png', null=True, upload_to='product_images', verbose_name='Изображение товара'),
        ),
    ]
