# Generated by Django 3.0.8 on 2020-09-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200927_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aviable',
            new_name='available',
        ),
    ]
